### ISSUE TITLE
Multiple target for download

### ISSUE THREAD

**Issue by darktweek** [jaymoulin/docker-jdownloader#100]
Hi !

I have trouble when I make multiple volumes for download files.
Here my docker config:
```yml
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1000:100
    volumes:
      - /home/tweek/jdownloader/cfg/:/opt/JDownloader/cfg
      - /mnt/tosh_1t/Séries_loo/:/opt/JDownloader/Séries_Loo
      - /mnt/wd_3t/Séries/:/opt/JDownloader/Séries
      - /mnt/wd_3t/Films/:/opt/JDownloader/Films
      - /mnt/lacie_1t/Films_Anime_Comics/DC&Marvel:/opt/JDownloader/DC&Marvel
      - /mnt/lacie_1t/Films_Anime_Comics/OAV/:/opt/JDownloader/OAV
      - /mnt/samsung_2t/Anime/:/opt/JDownloader/Anime
      - /mnt/lacie_1t/Dessin_Anime_pour_petit/Films/:/opt/JDownloader/Films_enfant
      - /mnt/lacie_1t/Dessin_Anime_pour_petit/Séries/:/opt/JDownloader/Séries_enfant
      - /home/tweek/jdownloader/logs/:/opt/JDownloader/logs #optional
      - /etc/localtime:/etc/localtime:ro #optional
    environment:
      MYJD_USER:  #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      MYJD_PASSWORD:  #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      MYJD_DEVICE_NAME: VegetaSSJ2 #optional
    ports:
      - 3129:3129
```
My trouble is, when I download to Download all is good, but if I I select a other path he doesn't make the file from the .part .

Can you help me ?
