### ISSUE TITLE
Invalid Download Directory

### ISSUE THREAD

**Issue by mimi-ac** [jaymoulin/docker-jdownloader#112]
Hello,
thank you for you work on jdownloader-docker.

I have a small problem:
I installed the docker-container on a omv-system by using the following compose-file:

```
services:  
jdownloader: 
image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1003:100
    volumes:
        - /srv/dev-disk-by-uuid-0/Appdata/jdownloader/jdownloaderConfig:/opt/JDownloader/app/cfg
        - /srv/dev-disk-by-uuid-0/downloads:/opt/JDownloader/Downloads
        - /srv/dev-disk-by-uuid-0/Appdata/jdownloader/jdownloaderLogs:/opt/JDownloader/app/logs
        - /etc/localtime:/etc/localtime:ro
    environment: 
            MYJD_USER: aa@aaa.de
            MYJD_PASSWORD: mypassword
            MYJD_DEVICE_NAME: myNAME
            XDG_DOWNLOAD_DIR: /srv/dev-disk-by-uuid-0/downloads
    ports:
        - 3129:3129
```
        
The installation works great and everthing seems fine but when i use the webgui of my.jdownloader i get the error:
"Invalid Download Directory"
I configure all directorys like this:
`chown -R 1003:100 downloads`

What did I wrong.

Thankx for help.
