### ISSUE TITLE
Not working with Libreelec on RPI4

### ISSUE THREAD

**Issue by Sleipnir-1** [jaymoulin/docker-jdownloader#115]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.0.3-armel
```

**Description**
I installed libreelec 10.0.2 on my Raspberry Pi 4 4GB and wanted to use jdownloader with it. The only possibility is to use docker, but I always get the errors shown below when starting the container.

**Docker compose I used to start the container**
```
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader2
    restart: always
    user : 0:0
    volumes:
        - /storage/JDownloader2/app/cfg:/opt/JDownloader/app/cfg
        - /media/Seagate\ Expansion\ Dr/Data/Download:/opt/JDownloader/Downloads
        - /storage/JDownloader2/app/logs:/opt/JDownloader/app/logs #optional
        - /etc/localtime:/etc/localtime:ro #optional
    environment: 
            MYJD_USER: ******** #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: ******** #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: RPI4 #optional
    ports:
        - 3129:3129 
```

**Steps to reproduce the issue:**
1. Enter Docker compose above in portainer, which runs on RPI 4 Libreelec.
2. Error appears.

**Describe the results you received:**

```
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
```
the above looped over and over.

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Provide some logs (`docker logs jdownloader`)**
see results.
<details>
<pre>
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar

</pre>
</details>

**Comment by Sleipnir-1** [comment]
```
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader2
    restart: always
    user : 0:0
    volumes:
        - /storage/JDownloader2/app/cfg:/opt/JDownloader/app/cfg
        - /var/media/Seagate Expansion Dr/Data/Download:/opt/JDownloader/Downloads
    environment: 
            MYJD_USER: dukester155@yahoo.de #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: supersport1 #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: RPI4 #optional
```

Additionally, I tried with this config and the `jdownloader-block.txt` to debug with my limited knowledge, but I wasn't able to find the problem.
