### ISSUE TITLE
Extensions cannot be installed because of permissions

### ISSUE THREAD

**Issue by d3f113** [jaymoulin/docker-jdownloader#116]
If you go to myJDownloader and try to install an extension like the eventscripter, it just shows some kind of progress, but nothing happens. Refreshing the site shows that.
This can be changed, if you change the owner of the extensions folder, like with the following command.
chown 1026:users /opt/JDownloader/extensions

 I don’t know, where this user comes from, but it has now the same permissions like the Downloads and cfg folder.
Perhaps something like that could be added to one of the scripts, so you don’t have to do that manually in the docker container

**Comment by b2un0** [comment]
just mount also the folder to keep them

as example

```yaml
version: "3.9"

services:
  jdownloader:
    image: jaymoulin/jdownloader:latest
    container_name: jdownloader
    network_mode: bridge
    restart: unless-stopped
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: "512MB"
          cpus: "1.0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/apps/jdownloader/config:/opt/JDownloader/app/cfg
      - /mnt/user/apps/jdownloader/logs:/opt/JDownloader/app/logs
      - /mnt/user/apps/jdownloader/extensions:/opt/JDownloader/app/extensions
      - /mnt/user/downloads/ddl:/opt/JDownloader/Downloads
```
