### ISSUE TITLE
Not working on rpi4, raspberrypi os 64bit

### ISSUE THREAD

**Issue by raaron773** [jaymoulin/docker-jdownloader#118]
Here's my docker-compose.yml

```
 version: "3.3"
 
 services:
   jdownloader:
     image: jaymoulin/jdownloader:latest
     container_name: JDownloader2
     restart: always
     user: 1000:1000
     ports:
       - "3129:3129"
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /home/pi/jdownloader2/config:/opt/JDownloader/app/cfg
       - /home/pi/jdownloader2/logs:/opt/JDownloader/app/logs
       - /mnt/ext-HDD/jdownloader2:/opt/JDownloader/Downloads
```
logs are here: https://pastebin.com/rhrgwKiu 
I am pretty sure it's something mundane which is going right past my eyes but I can't figure it out.
