### ISSUE TITLE
java.lang.RuntimeException: No Console Available!

### ISSUE THREAD

**Issue by peterpepo** [jaymoulin/docker-jdownloader#128]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.1.2-arm64
```

**Description**

Container fails to start *first time*, when docker-secret identification is used (FILE_MYJD_USER + FILE_MYJD_PASSWORD).

When the image is created with MYJD_USER and MYJD_PASSWORD, it starts successfully. I can then stop (or compose down, as long as config is persisted outside), switch back to FILE, start (or compose up) and it reads values from these secrets correctly. I have verified this by specifying other user/password in secrets and recreating (compose down; compose up) container, it connected to this alternative account.

It is only the very first time the container is run, MYJD_USER + MYJD_PASSWORD must be specified. Otherwise it produces following error in log - see log below in *Describe the results you received* section.

**Command line I used to start the container**
docker compose up -d

docker-compose.yml
```
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    network_mode: bridge
    user: 1000:1000
    volumes:
        - /home/pi/docker/jdownloader/data/config:/opt/JDownloader/app/cfg
        - /mnt/ds115j_rpi/JDownloader:/opt/JDownloader/Downloads
        - /home/pi/docker/jdownloader/data/logs:/opt/JDownloader/app/logs
        - /home/pi/docker/jdownloader/data/extensions:/opt/JDownloader/app/extensions
        - /etc/localtime:/etc/localtime:ro
    environment:
            FILE_MYJD_USER: myjd-user
            FILE_MYJD_PASSWORD: myjd-password
#            MYJD_USER: my@email.com
#            MYJD_PASSWORD: "my password is here"
            MYJD_DEVICE_NAME: rpi-jd-docker

    ports:
        - 3129:3129
    secrets:
        - myjd-user
        - myjd-password

secrets:
  myjd-user:
    file: /home/pi/docker/jdownloader/data/secrets/myjd_user.txt
  myjd-password:
    file: /home/pi/docker/jdownloader/data/secrets/myjd_password.txt
```

**Steps to reproduce the issue:**
1. specify container using docker compose
2. specify FILE_MYJD_USER + FILE_MYJD_PASSWORD
3. don't specify MYJD_USER + MYJD_PASWORD environmental variables
4. `docker compose up -d`
5. Fails with mentioned error
6. `docker compose down`
7. comment out FILE_MYJD_USER + FILE_MYJD_PASSWORD
8. uncomment MYJD_USER + MYJD_PASSWORD
9. `docker compose up -d`, successfull start
10. `docker compose down`
11. comment MYJD_USER + MYJD_PASSWORD
12. uncomment FILE_MYJD_USER + FILE_MYJDT_PASSWORD
13. `docker compose up -d`
14. now works

**Describe the results you received:**
```
java.lang.ExceptionInInitializerError
	at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:746)
Caused by: java.lang.RuntimeException: No Console Available!
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.askLoginsOnConsole(MyJDownloaderController.java:273)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:125)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:112)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:37)
	... 1 more
```

**Describe the results you expected:**
Successful container start.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have verified and double checked, that the secrets are correctly loaded on first container build by bashing into container with following output:
```
I have no name!@0fe2c53a0fbc:/opt/JDownloader$ cat "/run/secrets/$FILE_MYJD_USER"
my@email.com
I have no name!@0fe2c53a0fbc:/opt/JDownloader$ cat "/run/secrets/$FILE_MYJD_PASSWORD"
my password is here
I have no name!@0fe2c53a0fbc:/opt/JDownloader$
```

It seems like it has to be run with user+password specified explicitly for the first time, then I can switch to secrets.

I have inspected daemon.sh - https://github.com/jaymoulin/docker-jdownloader/blob/master/daemon.sh and it doesn't make any sense to me, I don't see any difference between configure with file or explicit, but it behaves this way. I'm puzzled.
**Provide some logs (`docker logs jdownloader`)**
