### ISSUE TITLE
usermod: user 'jdown' does not exist

### ISSUE THREAD

**Issue by trohnjavolta** [jaymoulin/docker-jdownloader#136]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.2.4-linux/amd64
```

**Description**

**Compose File I used to start the container**
```
jdownloader2:
    container_name: jdownloader2
    environment:
      - GID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    network_mode: "container:gluetun"
    image: jaymoulin/jdownloader
    restart: always
    user: 1000:100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_STORAGE}/downloads/jdownloads:/opt/JDownloader/Downloads
      - ${DOCKER_VOLUME_CONFIG}/jd2:/opt/JDownloader/app/cfg
```

**Steps to reproduce the issue:**
1. Start jdownloader2 container

**Describe the results you received:**
```
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
```

**Describe the results you expected:**
Normally start jdownloader2

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal
usermod: user 'jdown' does not exist
groupmod: Cannot determine your user name.
su: must be run from a terminal</pre>
</details>

**Comment by jaymoulin** [comment]
Thank you for using this repository. As you may know, maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

If you can use user flag (which you can), don't use PUID/GID env. It's only a workaround. But your mistakes shows a flaw in the code to anticipate this behaviour

**Comment by trohnjavolta** [comment]
What do you mean by user flag, the line `user:` in compose-overrides file? I tried that, it also doesn't work. I'm using dockstarter.com which uses environment variables, also for group and userid and recommended way is using environment variables `- GID=${PGID} - PUID=${PUID}`. Idk how to solve this problem, that didn't exist up until now.

**Comment by jaymoulin** [comment]
I don't know that dockstarter.com system and why you don't use docker if your system allows it. What I know, is user flag (yes, user attribute in compose file) and PUID/GID env MUST NOT be used at the same time. User flag will change user execution of your container and is incompatible with id change if you're not root (no user flag) as described in the documentation. I don't know what "doesn't work" in your " tried that, it also doesn't work" statement, but I know that if you can use user flag, use it. The PUID/GID env feature is a workaround. You can use it ONLY if you can't change the user with that user flag. Don't do both

**Comment by cmprinho** [comment]
> What do you mean by user flag, the line `user:` in compose-overrides file? I tried that, it also doesn't work. I'm using dockstarter.com which uses environment variables, also for group and userid and recommended way is using environment variables `- GID=${PGID} - PUID=${PUID}`. Idk how to solve this problem, that didn't exist up until now.

I encountered the similar issue when updating an old instance.
As @jaymoulin already described. Simply remove the `-GID= .. and -PUID=...` part and user the docker-compose provided `user` snippet:

```
jdownloader2:
    container_name: jdownloader2
    environment:
      - TZ=${TZ}
    network_mode: "container:gluetun"
    image: jaymoulin/jdownloader
    restart: always
    user: ${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_STORAGE}/downloads/jdownloads:/opt/JDownloader/Downloads
      - ${DOCKER_VOLUME_CONFIG}/jd2:/opt/JDownloader/app/cfg
```

I tested it on my machine and it works as expected. Somewhere was a "breaking change" but nothing wild.
