### ISSUE TITLE
Configuration for direct mode using gluetun

### ISSUE THREAD

**Issue by Turiok** [jaymoulin/docker-jdownloader#140]
Hi,

I've been using this image for years with the direct mode of activation. 
Some time ago, I changed my configuration to use a VPN through the gluetun image. 
Since then, I can no longer use direct mode. 
Would you know how to configure direct mode with this change?

**Comment by derlocke-ng** [comment]
facing the same issue currently, manual ip(s), port, rebind-protection whitelisting or changing dns servers did not help. still dns rebind protection error. I can `curl 127.0.0.1:3129` and get `curl: (52) Empty reply from server`, but with my lan ip i get `curl: (56) Recv failure: Connection reset by peer`.

edit:
my compose file:

```
#version: '3.8'


services:
  knvpn-client:
    image: qmcgaw/gluetun
    container_name: knvpn-client
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=$VPN_PROVIDER
      - VPN_TYPE=$VPN_TYPE
      - TZ=$TZ
      - WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL=25s
      - DOT_PROVIDERS=$DOT_PROVIDERS
      - WIREGUARD_MTU=$WIREGUARD_MTU
#      - FIREWALL_VPN_INPUT_PORTS="80,443,3129"
#      - FIREWALL_OUTBOUND_SUBNETS="172.128.0.0/24,10.8.0.0/24"
#        - FIREWALL_INPUT_PORTS="80,443,3129"
    networks:
      knet-node:
        ipv4_address:  172.128.0.2
    ports:
      - 3129:3129
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    volumes:
#      - $DOCKERDIR/kmvpn-client/start.sh:/start.sh
      - $DOCKERDIR/knvpn-client/$WG_CONFIG:/gluetun/wireguard/wg0.conf
      - $DOCKERDIR/knvpn-client/post-rules.txt:/iptables/post-rules.txt
    sysctls:
      - net.ipv4.tcp_mtu_probing=1
      - net.ipv4.tcp_base_mss=1024
#    entrypoint: ["sh", "/start.sh"]

## knpihole
  knpihole:
    image: pihole/pihole
    container_name: knpihole
    environment:
      - WEBPASSWORD=$PW_PIHOLE
      - TZ=$TZ
      - PIHOLE_DNS_=$PIHOLE_DNS_
      - DNSMASQ_LISTENING=all
      - FTLCONF_webserver_domain=$PIHOLE_HOSTNAME
    volumes:
      - '$DOCKERDIR/knpihole/etc-pihole:/etc/pihole'
      - '$DOCKERDIR/knpihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "127.0.0.1:8080:80/tcp"
      - "8080:80/tcp"
    restart: unless-stopped
    networks:
      knet-node:
        ipv4_address: 172.128.0.4
    hostname: pihole
    cap_add:
      - CAP_SYS_TIME
      - NET_ADMIN
#    network_mode: "service:knvpn-client"
    logging:
      driver: "json-file"
      options:
        max-size: 10m

  kndhcphelper:
    restart: unless-stopped
    container_name: kndhcphelper
    network_mode: "host"
    image: homeall/dhcphelper:latest
    environment:
      IP: '172.128.0.4'
      TZ: $TZ
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: 10m

## knnginx
  knnginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: knnginx
    depends_on:
     - knvpn-client
     - kntransmission
    ports:
    - 80:80
    - 443:443
    volumes:
     - $DOCKERDIR/knnginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - $DOCKERDIR/knnginx/fullchain.pem:/etc/nginx/fullchain.pem:ro
     - $DOCKERDIR/knnginx/privkey.pem:/etc/nginx/privkey.pem:ro
#    network_mode: "service:knvpn-client"
    networks:
      knet-node:
        ipv4_address: 172.128.0.5
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        
## knjdownloader        
  knjdownloader:
    image: jaymoulin/jdownloader
    container_name: knjdownloader
    restart: unless-stopped
    user: 1001:100
    depends_on:
     - knnginx
    volumes:
        - $DOCKERDIR/knjdownloader/cfg:/opt/JDownloader/app/cfg
        - $DL_DIR/downloads:/opt/JDownloader/Downloads
        - /etc/localtime:/etc/localtime:ro
    environment: 
            MYJD_USER: $MYJD_USER
            MYJD_PASSWORD: $MYJD_PASSWORD
            MYJD_DEVICE_NAME: $JD_HOSTNAME
    network_mode: "service:knvpn-client"
    logging:
      driver: "json-file"
      options:
        max-size: 10m

## kntransmission
  kntransmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: kntransmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - USER=$TMUSER
      - PASS=$TMPASS
    volumes:
      - $DOCKERDIR/kntransmission/config:/config
      - $DL_DIR/downloads:/downloads
    restart: unless-stopped
    network_mode: "service:knvpn-client"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        
## knportainer
  knportainer:
    image: portainer/portainer-ce:latest
    container_name: knportainer
    ports:
        - 127.0.0.1:9443:9443
    volumes:
        - portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      knet-node:
        ipv4_address: 172.128.0.250
    logging:
      driver: "json-file"
      options:
        max-size: 10m
## knsftp

  knsftp:
    image: jmcombs/sftp
    container_name: knsftp
    volumes:
        - $DL_DIR/downloads:/home/user/Downloads
    ports:
        - "2224:22"
    command: $SFTPUSER:$SFTPPASS:1001
    networks:
      knet-node:
        ipv4_address: 172.128.0.251
    logging:
      driver: "json-file"
      options:
        max-size: 10m

networks:
  knet-node:
    name: knet-node  
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: knet-node
      com.docker.network.driver.mtu: 1412
    ipam:
      driver: default
      config:
      - subnet: 172.128.0.0/24
        gateway: 172.128.0.1

volumes:
  portainer_data:
    name: portainer_data
#      external: true
```
and my post-rules.txt:
```
# gw docker container network
#iptables -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED,NEW -j ACCEPT
iptables -A FORWARD -i eth0 -o eth0 -j REJECT
iptables -A FORWARD -s 172.128.0.0/24 -o tun0 -j ACCEPT

# nginx
iptables -t nat -A PREROUTING -d 10.8.0.6 -p tcp --dport 443 -j DNAT --to-destination 172.128.0.5:443
iptables -t nat -A PREROUTING -d 10.8.0.6 -p tcp --dport 80 -j DNAT --to-destination 172.128.0.5:80
iptables -t nat -A PREROUTING -d 10.8.0.6 -p tcp --dport 2222 -j DNAT --to-destination 172.128.0.5:2222

# jdownloader
iptables -t nat -A PREROUTING -d 10.8.0.6 -p tcp --dport 3129 -j DNAT --to-destination 172.128.0.2:3129

# sftp
iptables -t nat -A PREROUTING -d 10.8.0.6 -p tcp --dport 2224 -j DNAT --to-destination 172.128.0.251:22

#restinpeace
#iptables -t nat -A POSTROUTING -m conntrack --ctstate DNAT -j MASQUERADE
iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE


# gw host local network
#iptables -A FORWARD -s 172.17.0.0/24 -o tun0 -j ACCEPT


# We should permit replies to traffic we've sent out.
iptables -A INPUT -i tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT
```

edit2:
found this in the jdownloader logs after curling:
```
java.lang.NullPointerException
	at org.jdownloader.api.myjdownloader.MyJDownloaderHttpConnection.getOutputStream(MyJDownloaderHttpConnection.java:347)
	at org.jdownloader.api.myjdownloader.MyJDownloaderHttpConnection.closeConnection(MyJDownloaderHttpConnection.java:285)
	at org.appwork.utils.net.httpserver.HttpConnection.run(HttpConnection.java:561)
	at org.jdownloader.api.myjdownloader.MyJDownloaderDirectServer$6.run(MyJDownloaderDirectServer.java:444
```
