### ISSUE TITLE
Cannot use Direct connection when using bridge networking

### ISSUE THREAD

**Issue by auanasgheps** [jaymoulin/docker-jdownloader#36]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
0.7.2-amd64
```

**Description**

Cannot use Direct connection when using bridge networking. I guess this is happening because the container is announcing the virtual docker IP, in my case 172.20.0.6, and my public IP. I can see these IP addresses from the android app. I have not opened a port from WAN access.

I want to use direct connection only in my LAN, but currently it is not possible.

**Command line I used to start the container**
```
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    user: 1029:100
    volumes:
        -/path/to/cfg/on/host:/opt/JDownloader/cfg
        -/path/to/logs/on/host::/opt/JDownloader/logs
        -/path/to/downloads/on/host:/downloads
        -/etc/localtime:/etc/localtime:ro
    ports:
        - 3129:3129 
    networks:
        default:
            ipv4_address: 172.20.0.6    
    
networks:
    default:
        external: 
            name: rete
### Note: "rete" is an already existing bridge network.
```
**Steps to reproduce the issue:**
1. Deploy the container with this configuration (bridge docker network) 
2. Set Jdownloader to "Allow lan/wan connections with manual port forwarding"
3. Restart the container

**Describe the results you received:**
Connection will remain on Jdownloader servers

**Describe the results you expected:**
Direct connection to be enabled

**Additional information you deem important (e.g. issue happens only occasionally):**
I believe we need to tell the container that the real local IP is another one.

**Provide some logs (`docker logs jdownloader`)**
Do you really need logs for this? What file exactly?
<details>
<pre>
(paste logs)
</pre>
</details>
