### ISSUE TITLE
Problem when password with comma

### ISSUE THREAD

**Issue by Turiok** [jaymoulin/docker-jdownloader#46]
Hello and thx for your works.

Using newly env variable MYJD_USER and MYJD_PASSWORD in my docker compose.
I found a bug.
Before that I edited manually the file :
org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json

In my actual password I have a "," and with the script configure.sh, the sed command failed because the comma.
I'm not an regex expert to prevent this. But I think a little note in your README to be careful with comma password.

Example : 
If I have in the file, the line : 
```
"password" : "test,test",
```
and in my docker compose, I have :
```
jdownloader:
    image: jaymoulin/jdownloader
    restart: "unless-stopped"
    ports:
       - 3129:3129
    environment: 
       - UID=${JDOWNLOADER_UID}
       - GID=${JDOWNLOADER_GID}
       - MYJD_USER=${JDOWNLOADER_ID}
       - MYJD_PASSWORD=test,test
      ...
```

After docker-compose up -d.
The modified line is : 
```
"password" : "test,test",test",
```

Sorry for the language. It's not my native

Sincerely,
Turiok
