### ISSUE TITLE
Follow-up of #23 - Unable to extract RAR archives with password

### ISSUE THREAD

**Issue by auanasgheps** [jaymoulin/docker-jdownloader#49]
This is a followup of #23 
After a lot of time I had the time to do more "scientific" testing.

This time around:
**Container Version**: 1.2.0-amd64
**Docker**: 19.0.3
**Host OS**: Debian 10

My Docker file
```
version: "2"

services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    user: 1001:1001
    volumes:
        - /path/to/cfg:/opt/JDownloader/cfg
        - /path/to/logs:/opt/JDownloader/logs
        - /path/to/downloads:/downloads
        - /etc/localtime:/etc/localtime:ro
    environment: 
            MYJD_USER: blip
            MYJD_PASSWORD: blop  
    ports:
        - 3129:3129 
    networks:
        default:   
        
networks:
    default:
        external: 
            name: rete
```

Try downloading this test file I made from my PC using WINRAR 5.60. It's actually a RAR4 file.

`drive . google .com /file/d/1o8QoAvEQIldd-pYKAcG6fXCcs9pNZlWl`

Password is `pmkv`
It crashes.
