### ISSUE TITLE
Direct connection from My JDownloader not working

### ISSUE THREAD

**Issue by ItalyPaleAle** [jaymoulin/docker-jdownloader#61]
I am having the same issues as #36 (issue is locked and can't comment there). I followed all instructions, but I can't get My JDownloader to connect to the container directly.

The container is running on a host with IP `10.1.1.20`, and port 3129 is exposed. Following the instructions, I've configured "Custom device IPs" to `["10.1.1.20"]`. I've told JDownloader to allow connections from LAN and WAN. Port is set manually to 3129 (no UPNP), both local and remote. I am using bridge mode because there are other containers running on the same host.

There are no firewalls blocking connections to port 3129 from inside the LAN. From my laptop, running `curl https://10.1.1.20:3129 -k` shows that it does connect (there's no response because I don't know the APIs, but it shows the correct TLS certificate)

However, the MyJDownloader service still goes through the relay and can't connect directly to my container.

I've honestly ran out of ideas and any help would be highly appreciated.

Below, my Docker Compose file:

```yaml
version: '3.4'
services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: "daemon"
    volumes:
      - /var/containers/jdownloader/config:/opt/JDownloader/cfg
      - /data/nas/Download:/download
    ports:
      - "3129:3129"
```

Thank you!
