### ISSUE TITLE
selected file not found after downlods

### ISSUE THREAD

**Issue by jekkii** [jaymoulin/docker-jdownloader#67]
hi, my set config in this:
```
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1000:1000
    volumes:
        - /srv/dev-disk-by-label-datadisk/appdata/config/jdownloader:/opt/JDownloader/cfg
        - /srv/dev-disk-by-label-datadisk/JDownloader2:/opt/JDownloader/Downloads
    environment: 
            MYJD_USER: xxxxxx
            MYJD_PASSWORD:   xxxxx
	    XDG_DOWNLOAD_DIR: /JDownloader2
    ports:
        - 3129:3129 
```
apparently it works but I can't find the downloaded files in the folder.
how do i set it to work?
folders have all permissions.
UID and GID are correct, qbittorrent works perfectly with these.
I set everything up through "create container"
can you help me?

EDIT: in settings on Myjdownloader page -> storage  show me this:
![qweqweqwewqe](https://user-images.githubusercontent.com/64632640/81055094-4b878f00-8ec8-11ea-8d3a-8716b7490b84.png)
but it's not the storage hard drive that I chose at the time of the container set
