### ISSUE TITLE
unable to see server in "myjdownloader" website

### ISSUE THREAD

**Issue by studiojurdan** [jaymoulin/docker-jdownloader#77]
i'd tryed the docker compose on RPI4 and omv 5 but if the service is running i can't see it in "myjdowloader"

I also add....but nothing change
`sudo docker exec jdownloader configure studio-jurdan@prfghail.ch Password`

Docker compose edit...

```
version: 2
services:
  jdownloader-2:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1001:100
    volumes:
        - /srv/dev-disk-by-label-intenso_5t/Config:/opt/JDownloader/cfg
        - /srv/dev-disk-by-label-intenso_5t/Torrents/opt/JDownloader/Downloads:/opt/JDownloader/Downloads
    environment: 
            MYJD_USER: studio-jurdan@prail.ch 
            MYJD_PASSWORD: Password 
            MYJD_DEVICE_NAME: raspi4 
    ports:
        - 3129:3129
```
