### ISSUE TITLE
encoding issue - non English characters

### ISSUE THREAD

**Issue by valkodev** [jaymoulin/docker-jdownloader#83]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
1.4.2-amd64

```

**Description**

When downloading files which contains a non English characters, files are showing in My JDownloader web interface properly but are store wrongly after download. I did a lot of testing and tried to solve the problem. I had same issue when using JDownloader installed on Ubuntu 20.04 and this was solved by starting the application of using (java -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -jar JDownloader.jar) - more details on the JDownloader support web: https://board.jdownloader.org/showthread.php?t=67428

They also demanding proper locales to be set. I guess this is actually the issue with your image, probably due to the fact is is based on Alpine, but not sure on this one.

I tried to set locales (LC_CTYPE="en_US.UTF-8", LANG="en_US.UTF-8", LC_COLLATE="C", LANGUAGE=en_US.UTF-8, LC_ALL=en_US.UTF-8) in docker and inside container, printenv is showing proper locales environments. But JDownloader log file is showing that it is still using wrong "sun.jnu.encoding=ANSI_X3.4-1968". Based on the above forum, they stating I have to set export environments inside the script. So I tried to modify daemon.sh, added export of locales et the beginning:

```bash
#!/bin/sh

export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_COLLATE="C"
export LANGUAGE=en_US.UTF-8 
export LC_ALL=en_US.UTF-8
```

but jdownloader is still showing wrong encoding in the log "sun.jnu.encoding=ANSI_X3.4-1968". and the file has a wrong name.

Modifying daemon.sh java command to:

java -Dsun.jnu.encoding=UTF-8 -Djava.awt.headless=true -jar /opt/JDownloader/JDownloader.jar -norestart &

will finally solve the java encoding to be "sun.jnu.encoding=UTF-8" but the issue is not solved.

Now when downloading, there is a zero size file created with proper name, ending .part and second file with wrong name, ending .part. The downloading is done to the wrong file and final file has wrong name. The zero size file will never get deleted by Jdownloader.

**Command line I used to start the container**
I use docker compose:
```yaml
version: "2.4"
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    volumes:
        - path/to/config:/opt/JDownloader/cfg
        - path/to/Downloads:/opt/JDownloader/Downloads
        - path/to//logs:/opt/JDownloader/logs #optional
        - /etc/localtime:/etc/localtime:ro #optional
    environment:
            MYJD_USER: my user #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: my pwd #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: Docker Server #optional
            XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads #optional
    ports:
        - 3129:3129
```

**Steps to reproduce the issue:**
1. verify java encoding by inspecting log file: cat Log.L.log.0 |grep encoding 

2. Try to download any file with non English characters, for example:  https://uloz.to/file/bQvtNyy9wNCZ/t6-obyvaci-stena-rez-pdf

2. Verify locally stored file, it has name "T6 - OB?VAC? ST?NA - ?EZ .pdf" instead a correct one "T6 - OBÝVACÍ STĚNA - ŘEZ .pdf"

3. Modify the daemon.sh, add " -Dsun.jnu.encoding=UTF-8" to the java run command

4. delete previously downloaded data / files and restart container or kill java process

5. Download same file again,  for example:  https://uloz.to/file/bQvtNyy9wNCZ/t6-obyvaci-stena-rez-pdf

6. Verify locally stored files, now there are 2 files, one has name "T6 - OB?VAC? ST?NA - ?EZ .pdf" iand second / empty one has name "T6 - OBÝVACÍ STĚNA - ŘEZ .pdf.part"

**Describe the results you received:**

T6 - OB?VAC? ST?NA - ?EZ .pdf

**Describe the results you expected:**

T6 - OBÝVACÍ STĚNA - ŘEZ .pdf.part

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
(paste logs)
</pre>
</details>
