### ISSUE TITLE
Error No Console Available!

### ISSUE THREAD

**Issue by serocult1** [jaymoulin/docker-jdownloader#89]
Hi,

I have tried install jdownloader with portainer. All is ok, but when run i have the next error:

> 33|Log.L.log 2/14/21, 4:40:42 PM - SEVERE [ Log.L.log ] -> Exception thrown at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:889):
> java.lang.ExceptionInInitializerError at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:717)
> Caused by: java.lang.RuntimeException: No Console Available!
> 	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
> 	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
> 	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:118)
> 	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:107)
> 	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:32)
> 	... 1 more
> 

This is my docker-compose:

> version: 2
> services:
>    jdownloader:
>     image: jaymoulin/jdownloader
>     container_name: jdownloader
>     restart: always
>     user: 998:100
>     volumes:
>         - /srv/dev-disk-by-uuid-e0c6c0e1-2dbb-4189-b7f8-5050c56b0fbb/jdownloader2:/opt/JDownloader/cfg
>         - /srv/dev-disk-by-uuid-e0c6c0e1-2dbb-4189-b7f8-5050c56b0fbb/Descargas:/opt/JDownloader/Downloads
>         - /etc/localtime:/etc/localtime:ro
>     environment: 
>             MYJD_USER: user@gmail.com
>             MYJD_PASSWORD: dummy
>             MYJD_DEVICE_NAME: sata
>             XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads
>     ports:
>         - 3129:3129

Anyone help me to solve it?

Thanks

**Comment by Sammydlux** [comment]
Good luck getting someone to help you.

Can you connect and download something over myjdownloader.com?
My console is broken too, that's the only way it works for me.

**Comment by serocult1** [comment]
No, i Can't connect. When I go to myjdownloader not appear nothing

**Comment by gentlemenVap** [comment]
I have the same issue. To connect to myjdownloader you need to login to your account btw!
docker exec jdownloader configure email@email.com password

this command should log you in, change to your info btw.

**Comment by StormPooper** [comment]
Having the same issue, tried all the above as well as recreating the container, but no luck.

**Comment by ryanamaral** [comment]
I have the exact same issue. I've been trying everything for hours, even downgrading but no luck as well.

Here is my configuration:
```
version: "2.1"
services:
   jdownloader:
    image: jaymoulin/jdownloader:latest
    container_name: jdownloader
    stdin_open: true. # docker run -i
    tty: true  # docker run -t
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYJD_USER=****
      - MYJD_PASSWORD=****
      - MYJD_DEVICE_NAME=rpi4-32bit
      - XDG_DOWNLOAD_DIR=/opt/JDownloader/Downloads
    volumes:
      - /srv/dev-disk-by-uuid-8b050af3-6966-4199-bc7b-252ece061be4/JDownloader/Config:/opt/JDownloader/cfg:rw
      - /srv/dev-disk-by-uuid-8b050af3-6966-4199-bc7b-252ece061be4/JDownloader/Logs:/opt/JDownloader/logs:rw
      - /srv/dev-disk-by-uuid-8b050af3-6966-4199-bc7b-252ece061be4/JDownloader/Downloads:/opt/JDownloader/Downloads:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3129:3129
```

The only thing I can think off right now is this build not being compatible with 32 bits.
