### ISSUE TITLE
Cannot get container to start

### ISSUE THREAD

**Issue by YouveGotMeowxy** [jaymoulin/docker-jdownloader#92]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
1.4.3-amd64
```

**Description**

Container won't start.

Logs seems  to point to  perms error,  but  I have  done this  on the WSL2 host:

`id ash`

     uid=1000(ash) gid=1000(ash) groups=1000(ash),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),117(netdev),1001(docker)

I have even done :

`sudo chown ash:ash /opt/docker/configs/jDownloader`

and 

`sudo chown ash:ash /opt/docker/logs/jdownloader`

**Command line I used to start the container**

```
    jdownloader2:
        hostname: jdownloader2
        image: jaymoulin/jdownloader:latest
        environment:
          - TZ=America/Chicago
        user: '1000:1000'
        volumes:
          - /opt/docker/configs/jDownloader/config:/opt/JDownloader/cfg:rw
          - /opt/docker/logs/jdownloader:/opt/JDownloader/logs:rw
          - /mnt/f/Fetched Media/Unsorted:/opt/JDownloader/Downloads:rw
          - /etc/localtime:/etc/localtime:ro
        ports:
          - 9023:5800
          - 3129:3129 
        networks:
          - od
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
            condition: any
```

**Describe the results you received:**
container stops on startup. Looks like permissions error, but not sure why.

**Describe the results you expected:**
to be able to start the container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

https://pastebin.com/ki6nAHZt
